### ISSUE TITLE
Matrix: not compatible - cmake changes needed

### ISSUE THREAD

**Issue by MilhouseVH** [notspiff/imagedecoder.mpo#9]
Doesn't build with latest Kodi master - requires cmake changes, I think. Also a Matrix branch.

Build log: http://ix.io/2hsm

**Comment by AlwinEsch** [comment]
Has started with them https://github.com/xbmc/imagedecoder.mpo/pull/8 and also on another addon.

I bring them now in to have it fixed.

**Comment by AlwinEsch** [comment]
Matrix branch now present and usable inside repo-binary-addons and here.
